# Site settings
title: LaurA to Z
email: jhclaura@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place for Programming From A to Z, by Daniel Shiffman, Fall 2015.
baseurl: /A-to-Z # the subpath of your site, e.g. /blog/
url: http://jhclaura.github.io/A-to-Z # the base hostname & protocol for your site
twitter_username: jhclaura
github_username:  jhclaura

# Build settings
markdown: kramdown
highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/A-to-Z/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


